# Generated by Django 4.0.1 on 2024-12-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_member_id_roommember_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
