# Generated by Django 4.0.1 on 2024-12-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_remove_roommember_is_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='room_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
